version: '2'
services:
  auth-service:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile 
    ports:
      - "7070:7070"
    volumes:
      - ./auth-service:/app
    depends_on:
      - mongodb
  
  order-service:
    build: 
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - ./order-service:/app
    depends_on:
      - mongodb
    
  product-service:
    build: 
      context: ./product-service
      dockerfile: Dockerfile 
    ports:
      - "8080:8080"
    volumes:
      - ./product-service:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: e-commece-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: