version: '2'
services:
  auth-service:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile 
    container_name: auth-service
    ports:
      - "7070:7070"
    volumes:
      - ./auth-service:/auth-service/app
    depends_on:
      - mongodb
  
  # order-service:
  #   build: 
  #     context: ./order-service
  #     dockerfile: Dockerfile
  #   container_name: order-service
  #   ports:
  #     - "9090:9090"
  #   volumes:
  #     - ./order-service:/order-service/app
  #   depends_on:
  #     - mongodb
    
  product-service:
    build: 
      context: ./product-service
      dockerfile: Dockerfile 
    container_name: product-service
    ports:
      - "8080:8080"
    volumes:
      - ./product-service:/product-service/app
    depends_on:
      - mongodb
      - rabbitmq

  mongodb:
    image: mongo
    container_name: e-commece-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/data/rabbitmq
    

volumes:
  mongodb-data:
  rabbitmq: