version: '2'

services:
  auth-service:
    build: 
      context: ./auth-service
      dockerfile: Dockerfile 
    container_name: auth-service-container
    ports:
      - "7070:7070"
    volumes:
      - ./auth-service:/auth-service/app
    depends_on:
      - mongodb-service
    networks:
      - e-commerce-service-network
  
  order-service:
    build: 
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service-container
    ports:
      - "9090:9090"
    volumes:
      - ./order-service:/order-service/app
    depends_on:
      - mongodb-service
      - rabbitmq-service
    networks:
      - e-commerce-service-network
    
  product-service:
    build: 
      context: ./product-service
      dockerfile: Dockerfile 
    container_name: product-service-container
    ports:
      - "8080:8080"
    volumes:
      - ./product-service:/product-service/app
    depends_on:
      - mongodb-service
      - rabbitmq-service
    networks:
      - e-commerce-service-network

  mongodb-service:
    image: mongo
    container_name: e-commerce-mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - e-commerce-service-network

  rabbitmq-service:
    image: rabbitmq:3.12-management
    container_name: e-commerce-rabbitmq-container
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/data/rabbitmq
    networks:
      - e-commerce-service-network

networks:
  e-commerce-service-network:

volumes:
  mongodb-data:
  rabbitmq-data: